name: Run Python tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Python dependencies and teamproject module
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Check docstrings with darglint
        run: |
          cd teamproject
          darglint -s google -v 2 crawler.py
          darglint -s google -v 2 models.py
