name: Run Python tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install Python dependencies
        run: |
        python -m pip install --upgrade pip
        pip install pandas
        pip install pytest
        pip install requests
        pip install typing

      - name: Run tests with pytest
        run: pytest
