name: Run Python tests
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install Python dependencies and teamproject module
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install -e .

      - name: Run tests with pytest
        run: pytest -v
